[package]
name = "btle"
description = "Lightweight Bluetooth Low Energy Drivers. WIP and not in a fully working state."
version = "0.1.0"
license = "GPL-3.0-only"
readme = "README.md"
authors = ["AndrewGi <andrew@gilbrough.com>"]
edition = "2018"
repository = "https://github.com/AndrewGi/btle/tree/master"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bluez_async"]
bluez = ["nix", "libc", "hci"]
bluez_async = ["bluez", "async", "tokio/uds"]
async = ["tokio"]
hci = []
std = []
[dependencies]
nix = {version = "0.16.1", optional = true}
libc = {version = "0.2.66", optional = true}
tokio = {version = "0.2.11", optional = true}