[package]
name = "btle"
description = "Lightweight Bluetooth Low Energy Drivers. WIP and very not stable yet!! Designed for https://github.com/AndrewGi/BluetoothMeshRust"
version = "0.1.3"
license = "GPL-3.0-only"
readme = "README.md"
authors = ["AndrewGi <andrew@gilbrough.com>"]
edition = "2018"
repository = "https://github.com/AndrewGi/btle/tree/master"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["hci",  "std", "tokio_asyncs"]
bluez = ["nix", "libc", "std", "hci", "tokio/uds"]
winrt_drivers = ["winrt", "std"]
hci = []
hci_usb = ["hci", "rusb"]
asyncs = []
tokio_asyncs = ["asyncs", "tokio/time", "tokio/sync", "tokio/rt-core"]
async-std_asyncs = ["asyncs", "std", "async-std/std"]
std = ["futures-io/std"]
remote = ["std", "hci"]

[dependencies]
winrt = {version = "0.6.0", default_features = false, features = ["windows-devices", "windows-storage"], optional = true}
futures-core = {version = "0.3.4", default_features = false, features=["alloc"]}
futures-sink = {version = "0.3.4", default_features = false}
futures-io = {version = "0.3.4", optional = true}
nix = {version = "0.16.1", optional = true}
libc = {version = "0.2.66", optional = true}
tokio = {version = "0.2.13", optional = true, default_features = false}
async-std = {version = "1.5.0", optional =true, default_features = false}
rusb = {version = "0.5.5", optional = true}

[[example]]
name = "advertisement_dump"
required-features = ["bluez"]

[[example]]
name = "windows_test"
required-features = ["windows_drivers"]